version: '3.4'
services:
    node01:
        image: daocloud.io/buxiaomo/zookeeper:3.4.10
        networks:
            kafka:
                aliases:
                    - zk01
        environment:
            ZOOKEEPER_CONFIG: |
                id=1
                zookeeper.cluster=zk01:2888:3888,zk02:2888:3888,zk03:2888:3888
        volumes:
            - /var/lib/zookeeper:/var/lib/zookeeper:rw
            - /usr/share/zoneinfo/Asia/Shanghai:/etc/localtime:ro
        deploy:
            mode: replicated
            replicas: 1
            update_config:
                parallelism: 1
                delay: 10s
                order: stop-first
            # resources:
            #     limits:
            #         cpus: '2'
            #         memory: 1G
            #     reservations:
            #         cpus: '1'
            #         memory: 500M
            placement:
                constraints:
                    - node.labels.zookeeper.node01 == true
        logging:
            driver: json-file
            options:
                max-file: '3'
                max-size: 100m

    node02:
        image: daocloud.io/buxiaomo/zookeeper:3.4.10
        networks:
            kafka:
                aliases:
                    - zk02
        environment:
            ZOOKEEPER_CONFIG: |
                id=2
                zookeeper.cluster=zk01:2888:3888,zk02:2888:3888,zk03:2888:3888
        volumes:
            - /var/lib/zookeeper:/var/lib/zookeeper:rw
            - /usr/share/zoneinfo/Asia/Shanghai:/etc/localtime:ro
        deploy:
            mode: replicated
            replicas: 1
            update_config:
                parallelism: 1
                delay: 10s
                order: stop-first
            # resources:
            #     limits:
            #         cpus: '2'
            #         memory: 1G
            #     reservations:
            #         cpus: '1'
            #         memory: 500M
            placement:
                constraints:
                    - node.labels.zookeeper.node02 == true
        logging:
            driver: json-file
            options:
                max-file: '3'
                max-size: 100m

    node03:
        image: daocloud.io/buxiaomo/zookeeper:3.4.10
        networks:
            kafka:
                aliases:
                    - zk03
        environment:
            ZOOKEEPER_CONFIG: |
                id=3
                zookeeper.cluster=zk01:2888:3888,zk02:2888:3888,zk03:2888:3888
        volumes:
            - /var/lib/zookeeper:/var/lib/zookeeper:rw
            - /usr/share/zoneinfo/Asia/Shanghai:/etc/localtime:ro
        deploy:
            mode: replicated
            replicas: 1
            update_config:
                parallelism: 1
                delay: 10s
                order: stop-first
            # resources:
            #     limits:
            #         cpus: '2'
            #         memory: 1G
            #     reservations:
            #         cpus: '1'
            #         memory: 500M
            placement:
                constraints:
                    - node.labels.zookeeper.node03 == true
        logging:
            driver: json-file
            options:
                max-file: '3'
                max-size: 100m

networks:
    kafka:
        external: true